name: Compilar Firmware Marlin
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4  # Atualizado para v4
      - uses: actions/setup-python@v5 # Atualizado para v5
        with:
          python-version: '3.11'
      
      - name: Instalar PlatformIO
        run: pip install -U platformio

      - name: Compilar
        # Este comando tenta compilar o primeiro ambiente encontrado no platformio.ini
        run: pio run
